spring:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://localhost:3306/sustentabilidad
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
